### ISSUE TITLE
It do not support mobile

### ISSUE THREAD

**Issue by Mahakb** [EnlighterJS/EnlighterJS#103] opened 2020-04-29 09:27 UTC
The plugin seems to not support mobiles. The code do not appear properly in mobile. This seems not to be responsive. This should be improved. Other than that I just loved it. Everything else is superb.

**Comment by Mahakb** [comment] 2020-04-30 12:55
Hi , 
Please refer the screenshots attached. This is basically my blog where I have used Enlighter. It load perfectly on dekstop , but breaks on mobile. I have used Add Scroll option for text overflow. 

Is there something that I am missing or doing wrong?

<img width="458" alt="Capture" src="https://user-images.githubusercontent.com/15336805/80712659-e589b900-8b0f-11ea-87ef-9c8ecbe4837e.PNG">
![Screenshot_20200430-181928_Chrome](https://user-images.githubusercontent.com/15336805/80712371-89bf3000-8b0f-11ea-8b2e-38f7fe38881c.jpg)
![Screenshot_20200430-181934_Chrome](https://user-images.githubusercontent.com/15336805/80712378-8d52b700-8b0f-11ea-8e0f-b362927c8516.jpg)

**Comment by AndiDittrich** [comment] 2020-04-30 13:12
hmm..is looks like intended - what did you expect ?

**Comment by Mahakb** [comment] 2020-04-30 13:22
I except the code block to have a scroll(or code break to next line) inspite of scrolling the entire webpage.

**Comment by AndiDittrich** [comment] 2020-04-30 13:26
ah now i understand whats happening - can you provide a link to your site ?

**Comment by Mahakb** [comment] 2020-04-30 13:27
http://62x.d7b.myftpupload.com/

**Comment by AndiDittrich** [comment] 2020-04-30 13:36
thanks. the issue is related to your theme and content structure... you've put the Enlighter codeblocks into a list..this may cause the responsive issue - whats about the top image, is it responsive ?

just try to create a test post/page with a single Enlighter codeblock

-----

for example, this is how EnlighterJS looks like without issues:
![image](https://user-images.githubusercontent.com/1474107/80716536-0ba35f00-8af8-11ea-8edd-7addef7e7af8.png)

**Comment by Mahakb** [comment] 2020-04-30 13:38
Oh.. Okay .. Let me try with a test blog and Will let you know

**Comment by Mahakb** [comment] 2020-04-30 13:43
Hi Andi , 
Thanks.. I got that ! The issue was with the web page itself. It worked perfectly on the test blog .

**Comment by AndiDittrich** [comment] 2020-04-30 13:44
great! i'll close the issue

**Closed by AndiDittrich** 2020-04-30 13:44 UTC
Labels: EnlighterJS3, question
