### ISSUE TITLE
Buttons v Text for Toolbar

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/EnlighterJS#98] opened 2020-04-16 07:26 UTC
Hi!

I noticed that some themes (like **Monokai**) use **text buttons** for the toolbar:

![Toolbar1](https://user-images.githubusercontent.com/7985331/79426600-461ae100-7fbb-11ea-9d91-c174bac7f5fd.png)

And other themes (like **Godzilla**) use **graphic buttons** for the toolbar:

![Toolbar2](https://user-images.githubusercontent.com/7985331/79426723-76627f80-7fbb-11ea-9b67-bdafd414f3a5.png)

Is this something that could be configured via a setting to choose graphics v text?

Here are my observations so far:

- On my iPhone the text buttons wrap and obscure most of the code snippets. Maybe the toolbar should not show on small device screens at all? Else, the graphic version of the buttons would take less space.
- Should the graphic buttons have tooltips?
- Should the buttons toolbar float? At the moment if I scroll left the buttons scroll left too.

**Comment by AndiDittrich** [comment] 2020-04-16 09:38
Hi @ajtruckle ,

for now it is the intended behaviour: each theme can have its own button styles. due to the css complexity it is not possible to change this within the theme customizer, you have to edit the css/less files.

tooltips are currently missing for all kind of buttons (not implemented yet) - this will change in the future.

currently i have to easy solution to solve the issues with horizontal-scroll enabled - personally i avoid scrollbars when displaying sourcecode

**Comment by ajtruckle** [comment] 2020-04-16 09:45
> currently i have to easy solution to solve the issues with horizontal-scroll enabled - personally i avoid scrollbars when displaying sourcecode
I understand. If you are using a touchscreen device you can drag the view I assume. But on a PC if I don't show the scroll bars the user can't see the rest of the code (unless the expand it to view the raw content. I prefer the user have ability to see all the code.

**Comment by AndiDittrich** [comment] 2020-04-16 09:46
you can use the `break` styling

**Comment by ajtruckle** [comment] 2020-04-16 09:53
> you can use the `break` styling

You mean where it word-wraps to the next line. I suppose so. But I find the code harder to read sometimes. And on smaller devises wordwraps would get excessive. This is why I prefer one line. :)

No worries.

**Comment by AndiDittrich** [comment] 2020-04-16 09:54
ok i'll close the issue

**Closed by AndiDittrich** 2020-04-16 09:54 UTC
