### ISSUE TITLE
Colouring of the last line in the XSL code block?

### ISSUE THREAD

**Issue by ajtruckle** [EnlighterJS/EnlighterJS#124] opened 2020-08-01 17:27 UTC
Hi !

Another curious question for you:

![SyntaxColour](https://user-images.githubusercontent.com/7985331/89106688-cc9ce680-d423-11ea-894d-49021264bc83.png)

The last but one line:

`<xsl:value-of select="concat($DD, '/', $MM)" />`

In Visual Studio it looks like this:

![VS](https://user-images.githubusercontent.com/7985331/89106749-682e5700-d424-11ea-87e0-b7a8afe56665.png)

I can copy the code into my public forum so you don't need a log in if you like. It seems to be related to the `'` characters but this is legal XML code.

**Comment by ajtruckle** [comment] 2020-08-01 18:16
This is the XSL to save you retyping:

```
<xsl:template name="add-days-to-date">
  <xsl:param name="days-to-add"/>
  <xsl:param name="year" select="substring(Date/@ThisWeek, 2, 4)"/>
  <xsl:param name="month" select="substring(Date/@ThisWeek, 6, 2)"/>
  <xsl:param name="day" select="substring(Date/@ThisWeek, 8, 2)"/>
  <xsl:param name="a" select="floor((14 - $month) div 12)"/>
  <xsl:param name="y" select="$year + 4800 - $a"/>
  <xsl:param name="m" select="$month + 12*$a - 3"/>
  <xsl:param name="JDN" select="$day + floor((153*$m + 2) div 5) + 365*$y + floor($y div 4) - floor($y div 100) + floor($y div 400) - 32045 + $days-to-add" />
  <xsl:param name="f" select="$JDN + 1401 + floor((floor((4 * $JDN + 274277) div 146097) * 3) div 4) - 38"/>
  <xsl:param name="e" select="4*$f + 3"/>
  <xsl:param name="g" select="floor(($e mod 1461) div 4)"/>
  <xsl:param name="h" select="5*$g + 2"/>
  <xsl:param name="D" select="floor(($h mod 153) div 5 ) + 1"/>
  <xsl:param name="M" select="(floor($h div 153) + 2) mod 12 + 1"/>
  <xsl:param name="Y" select="floor($e div 1461) - 4716 + floor((14 - $M) div 12)"/>
  <xsl:param name="MM" select="format-number($M, '00')"/>
  <xsl:param name="DD" select="format-number($D, '0')"/>
  <xsl:value-of select="concat($DD, '/', $MM)" />
</xsl:template>
```

**Comment by AndiDittrich** [comment] 2020-08-01 19:24
duplicate of #108

**Closed by AndiDittrich** 2020-08-01 19:24 UTC
Labels: EnlighterJS3, bug, duplicate
