### ISSUE TITLE
Kotlin triple quotes

### ISSUE THREAD

**Issue by Alizoo** [EnlighterJS/EnlighterJS#55] opened 2019-03-07 12:41 UTC
When using triple quotes in Kotlin it often includes code beyond the closing quotes. Example:
val filePath = """c:\dir\somedir"""
will not close whereas
val nurseryRhyme = """Humpty Dumpty sat on a wall
        |Humpty Dumpty had a great fall
        |All the king's horses and all the king's men
        |Couldn't put Humpty together again""".trimMargin()
closes properly. Seems to be the | that makes the difference

**Comment by AndiDittrich** [comment] 2019-03-07 14:05
Hi @Alizoo 
and thanks for your report.

the issue is related to the tokenizer of EnlighterJS v2 - not the WordPress plugin.

it has already been fixed in v3 - therefore i will close the issue

![image](https://user-images.githubusercontent.com/1474107/53962076-7884ba00-40ea-11e9-9898-e518d3047c39.png)

best regards, Andi

**Closed by AndiDittrich** 2019-03-07 14:05 UTC
Labels: EnlighterJS2, bug, wontfix
