### ISSUE TITLE
Avoid adding a "closing html tag" to tag like objects inside <pre></pre> (not sure if it's a feature request or a bug report)

### ISSUE THREAD

**Issue by talgalili** [EnlighterJS/EnlighterJS#162] opened 2021-05-29 16:02 UTC
If my code includes any type of html-tag like code, the EnlighterJS code automatically adds a closing tag to it.
Given that I'm using EnlighterJS on code that include such tags, I keep getting these (wrongly) added closing HTML tags.

Example:
```
<pre>
# some code
<a_tag_like_text>
<fo><bar>
# some code
</pre>
```

Will become
```
<pre>
# some code
<a_tag_like_text>
<fo><bar>
# some code
</a_tag_like_text></fo></bar>
</pre>
```

Screenshot of this bug when using the 'single-theme.html' example from the EnlighterJS directory (I added only <test_bug>, and the JS added the </test_bug> text):

![image](https://user-images.githubusercontent.com/976006/120076826-34f23e00-c0b0-11eb-93b2-06eb8bcd7012.png)

Ideally, the solution is to either allow me to turn this feature off completely, or to be able to mention tags I'd like to exclude (although, in my case, I'd just opt to turn it off completely)

Thanks upfront.

**Comment by AndiDittrich** [comment] 2021-05-29 19:51
you're html is invalid - it's not caused by EnlighterJS - the opening/closing brackets need to be replaced by the related escape sequences `&lt;` `&gt`

**Comment by talgalili** [comment] 2021-05-30 05:23
Thanks @AndiDittrich  - I can manage it on my end so this won't happen. 
But in general, the behavior of the code to add a closing bracket is something that I think is worth having a control parameter (e.g.: current behavior, do nothing, or replace special characters with relevant escape characters).

WDYT?

**Comment by AndiDittrich** [comment] 2021-05-30 09:04
again...this is not caused by EnlighterJS - the XML parser of your webbrowser is adding the closing tag to the DOM tree to be able to render the page:

`<pre><test_bug><textnode><missing-node></pre>`

**Comment by talgalili** [comment] 2021-05-30 09:25
Interesting. I'm using the EnlighterJS plugin in WordPress. And when it is
off, these tags are not added. But only when it is on they are added (while
the code is not valid in both cases).

**Closed** 2021-05-30 11:17 UTC
Labels: duplicate, invalid
