### ISSUE TITLE
Wrong method highlight in php, when it is called non-static

### ISSUE THREAD

**Issue by oleg-dk** [EnlighterJS/EnlighterJS#182] opened 2021-11-29 09:26 UTC
Wrong method highlight in php, when it is called non-static (from object).
E.g. in code
```
<div id="<?= $this->getEditAreaId($areaId='editable_area'); ?>"><?php
    $filePath = '/include/collection/delivery.php';
    $APPLICATION->includeFile($filePath, $params=[], $opts=['SHOW_BORDER' => false]);
    $title = 'Изменить';
    $this->addEditAction($areaId, '/bitrix/admin/public_file_edit.php?path='.$filePath, $title);
?></div>
```
screenshot: https://i.imgur.com/0Oioc2L.png

It seems that it highlight as part of variable, but not a method.

EnlighterJS Syntax Highlighter 3.5.1

**Comment by AndiDittrich** [comment] 2022-01-16 20:13
Hi @oleg-dk 

thanks for your report, the issue has been fixed in the master branch (it was caused by the utf8 variable name support)

![image](https://user-images.githubusercontent.com/1474107/149676310-9c0f3ae2-880a-4618-b703-c9eaf4bec282.png)

**Closed by AndiDittrich** 2022-01-16 20:13 UTC
Labels: bug, EnlighterJS3

**Comment by oleg-dk** [comment] 2022-01-16 20:24
@AndiDittrich
on your screenshot it seems that in «$APPLICATION->» the hyphen («-») is highlighted as part of the variable, but not part of the arrow («->»).

**Comment by AndiDittrich** [comment] 2022-01-16 20:31
sry, forgot to add the hyphen to the regex. now the operators `::` and `->` are highlighted as `k3` instead of plain text

![image](https://user-images.githubusercontent.com/1474107/149676956-87b301e2-d512-48bf-a133-147698d1a5a6.png)
