### ISSUE TITLE
Enlighter won't work in first word

### ISSUE THREAD

**Issue by Irwanda04** [EnlighterJS/EnlighterJS#129] opened 2020-08-18 12:05 UTC
I'm new at this plugin. I just want to ask why it won't work in the very first word?
![Screenshot from 2020-08-18 18-52-53](https://user-images.githubusercontent.com/45300477/90510922-ee1d0280-e185-11ea-8bc4-cc11a5a1f412.jpg)

It works if I add space before. But I don't want to do that.

**Comment by Irwanda04** [comment] 2020-08-18 12:14
I used generic highlighting for that.
And here is if i add space
![Screenshot from 2020-08-18 19-10-12](https://user-images.githubusercontent.com/45300477/90511647-f6c20880-e186-11ea-975a-f0ceb1927007.jpg)

**Comment by Irwanda04** [comment] 2020-08-18 12:19
function abc(a:integer) : integer;
begin
	abc :=a*3-(a mod 7);
	{a}
end;

function ghi(x:integer;b:integer):integer;
begin
	if (b=1) then
		ghi := x
	else
		ghi := (x* ghi(x,b-1)) mod 100;
end;

function def(a:integer; b:integer) : integer;
begin
	if (b mod 2 = 1) and (b&gt;500) then
		def := ghi(a,b) mod 100
		{b}
	else
		def:=def(a, abc(b)) ;
end;

**Comment by AndiDittrich** [comment] 2020-08-18 12:26
it's caused by the regex rule within the generic ruleset - it currently requires a non word character before+after the keywords ("function" is just a keyword)

**Comment by AndiDittrich** [comment] 2020-08-18 12:30
![image](https://user-images.githubusercontent.com/1474107/90513007-4f7dab00-e15f-11ea-826b-9a0f839d46bd.png)

**Comment by AndiDittrich** [comment] 2020-08-18 12:32
fixed in the master branch

**Closed** 2020-08-18 12:32 UTC

**Comment by Irwanda04** [comment] 2020-08-18 12:33
Thank you!!
